// TYPES DRAGON
export const FETCH_DRAGON_NEW_REQUEST = "FETCH_DRAGON_NEW_REQUEST";
export const FETCH_DRAGON_NEW_SUCCEEDED = "FETCH_DRAGON_NEW_SUCCEEDED";

export const FETCH_GENERATION_REQUEST = "FETCH_GENERATION_REQUEST";
export const FETCH_GENERATION_SUCCEEDED = "FETCH_GENERATION_SUCCEEDED";

export const FETCH_NEXT_GENERATION_REQUEST = "FETCH_NEXT_GENERATION_REQUEST";

export const FETCH_PUBLIC_DRAGON_REQUEST = "FETCH_PUBLIC_DRAGON_REQUEST";
export const FETCH_PUBLIC_DRAGON_SUCCEEDED = "FETCH_PUBLIC_DRAGON_SUCCEEDED";

export const BUY_DRAGON_REQUEST = "BUY_DRAGON_REQUEST";

export const SET_DRAGON_MATE_REQUEST = "SET_DRAGON_MATE_REQUEST";

// TYPES AUTH
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCEEDED = "LOGIN_USER_SUCCEEDED";

export const SIGN_UP_USER_REQUEST = "SIGN_UP_USER_REQUEST";
export const SIGN_UP_USER_SUCCEEDED = "SIGN_UP_USER_SUCCEEDED";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCEEDED = "LOGOUT_USER_SUCCEEDED";

export const CHECK_AUTH_REQUEST = "CHECK_AUTH_REQUEST";
export const CHECK_AUTH_SUCCEEDED = "CHECK_AUTH_SUCCEEDED";
export const CHECK_AUTH_FAILED = "CHECK_AUTH_FAILED";

export const FETCH_ACCOUNT_INFO_REQUEST = "FETCH_ACCOUNT_INFO_REQUEST";
export const FETCH_ACCOUNT_INFO_SUCCEEDED = "FETCH_ACCOUNT_INFO_SUCCEEDED";

export const FETCH_ACCOUNT_DRAGON_REQUEST = "FETCH_ACCOUNT_DRAGON_REQUEST";
export const FETCH_ACCOUNT_DRAGON_SUCCEEDED = "FETCH_ACCOUNT_DRAGON_SUCCEEDED";

export const UPDATED_ACCOUNT_DRAGON_REQUEST = "UPDATED_ACCOUNT_DRAGON_REQUEST";
export const UPDATED_ACCOUNT_DRAGON_SUCCEEDED = "UPDATED_ACCOUNT_DRAGON_SUCCEEDED";

// TYPES ERROR
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

// TYPES UTIL
export const LOADING_DATA = "LOADING_DATA";
export const LOADED_DATA = "LOADED_DATA";
